version: '2'

services:
  mysql:
    restart: always
    image: lew21/mariadb:10.1
    environment:
      MYSQL_DATABASE: accounts

  migrate:
    restart: on-failure
    depends_on:
    - mysql
    build:
      context: .
    environment:
    - SECRET_KEY=x
    - DATABASE_URL=mysql://root@mysql/accounts
    command: django-admin migrate

  loaddata:
    restart: on-failure
    depends_on:
    - mysql
    build:
      context: .
    environment:
    - SECRET_KEY=x
    - DATABASE_URL=mysql://root@mysql/accounts
    command: django-admin loaddata devdata.yaml

  accounts:
    restart: on-failure
    depends_on:
    - mysql
    build:
      context: .
    environment:
    - DATABASE_URL=mysql://root@mysql/accounts
    - SECRET_KEY=x
    - BASE_URL=http://localhost.aiakosauth.io:2121/
    - INSECURE_END_SESSION_ENDPOINT
    ports:
    - "2121:80"
